---
name: Net-Route
version: v0.00_03
author:
  - 'Straton IT <tequeter@straton-it.fr>'
abstract: Portable interface to the routing table
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  IPC::Run3: 0
  Moose: 0
  NetAddr::IP: 0
  Readonly: 0
  version: 0.74
build_requires:
  Test::More: 0
  Test::Perl::Critic: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
provides:
  Net::Route:
    file: lib/Net/Route.pm
    version: v0.00_03
  Net::Route::Parser:
    file: lib/Net/Route/Parser.pm
    version: 275
  Net::Route::Parser::MSWin32:
    file: lib/Net/Route/Parser/MSWin32.pm
    version: 275
  Net::Route::Parser::linux:
    file: lib/Net/Route/Parser/linux.pm
    version: 272
  Net::Route::Table:
    file: lib/Net/Route/Table.pm
    version: 254
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
